### ISSUE TITLE
Add papers to leaderboard April

### ISSUE THREAD

**Issue by RicardoUsbeck** [KGQA/leaderboard#10]
* https://assets.researchsquare.com/files/rs-1563040/v1_covered.pdf?c=1650473022
* https://arxiv.org/pdf/2204.10194.pdf
* https://arxiv.org/pdf/2204.10629.pdf

**Comment by xixi019** [comment]
- https://assets.researchsquare.com/files/rs-1563040/v1_covered.pdf?c=1650473022 This paper tests the model on a synthetic dataset. 
- https://arxiv.org/pdf/2204.10194.pdf is added. 
- https://arxiv.org/pdf/2204.10629.pdf tests the models on subset of RUBQ and SimpleQuestions (1-hop questions only), I remember we do not add test results like this?

**Comment by RicardoUsbeck** [comment]
Indeed, subsets would introduce too much noise in the tables.

Closed by https://github.com/KGQA/leaderboard/pull/13 https://github.com/KGQA/leaderboard/pull/12 https://github.com/KGQA/leaderboard/pull/11
