### ISSUE TITLE
leaderboard to be updated on KQA-Pro

### ISSUE THREAD

**Issue by xixi019** [KGQA/leaderboard#101]
http://thukeg.gitee.io/kqa-pro/leaderboard.html
They have their own leaderboard and also baseline systems need to be added

**Comment by RicardoUsbeck** [comment]
Maybe in this case, we just link to them? What do all think @LongquanJiang @huntila ?

**Comment by xixi019** [comment]
that sounds like a good idea to me! Their leaderboard is very well-defined and resourceful.

**Comment by RicardoUsbeck** [comment]
Okay, so this is just about creating a rather blank page with a link to their leaderboard and having it on our "main" page so people can navigate to their leaderboard

**Comment by xixi019** [comment]
Added.
