### ISSUE TITLE
Download link not working for MLPQ dataset

### ISSUE THREAD

**Issue by acxcv** [KGQA/leaderboard#111]
Hi, I tried downloading the MLPQ dataset using the link provided at [KGQA/leaderboard/dbpedia/mlpq.md](https://github.com/KGQA/leaderboard/blob/gh-pages/dbpedia/mlpq.md). 
Unfortunately, the link doesn't work. Can anybody help?

**Comment by LongquanJiang** [comment]
Hello, Thanks a lot for your feedback. The author has removed the github repository of MLPQ. We will try to contact the author and get back to you soon.

**Comment by LongquanJiang** [comment]
Hi, please check out the [link](https://www.sciencedirect.com/science/article/abs/pii/S221457962300014X) and email the authors.
