### ISSUE TITLE
add paper "DeepMaven: Deep question answering on long-distance movie/TV show videos with multimedia knowledge extraction and synthesis"

### ISSUE THREAD

**Issue by xixi019** [KGQA/leaderboard#138]
https://assets.amazon.science/9b/d2/5b79087b4dbb827c4bea40b6706a/deepmaven-deep-question-answering-on-long-distance-movie-tv-show-videos-with-multimedia-knowledge-extraction-and-synthesis.pdf

**Comment by xixi019** [comment]
This is not a KGQA task in my opinion, since the dataset is not annotated against any KG. What do you think? @LongquanJiang

**Comment by LongquanJiang** [comment]
Yes. close the issue.
