### ISSUE TITLE
add dataset "MLPQ: A Dataset for Path Question Answering over Multilingual Knowledge Graphs"

### ISSUE THREAD

**Issue by xixi019** [KGQA/leaderboard#139]
https://www.sciencedirect.com/science/article/abs/pii/S221457962300014X

**Comment by LongquanJiang** [comment]
This dataset has already added. But the authors deleted the download link. Maybe now the dataset can be downloaded.

**Comment by xixi019** [comment]
"Data will be made available on request.", hmmm
