### ISSUE TITLE
Add results from SKILL

### ISSUE THREAD

**Issue by RicardoUsbeck** [KGQA/leaderboard#33]
https://arxiv.org/abs/2205.08184

**Comment by xixi019** [comment]
I am not sure whether the datasets evaluated in the article are KGQA datasets:

- [FreebaseQA](https://aclanthology.org/N19-1028.pdf): A QA dataset dependent on freebase, only offers entity, predicate and path, no SPARQL. See [this link.](https://raw.githubusercontent.com/kelvin-jiang/FreebaseQA/master/FreebaseQA-dev.json)
- WikiHop: A reading comprehension dataset based on document, distant supervised by wikidata.
- TriviaQA: A reading comprehension dataset based on document.
- NaturalQuestion: A reading comprehension dataset based on document.

**Comment by RicardoUsbeck** [comment]
Yes, freebaseQA is still a valid dataset although there is no SPARQL provided. The others are not, you are right!

**Comment by xixi019** [comment]
> 
Thanks for reply, I will add freebaseQA and eval result from this paper soon!
