### ISSUE TITLE
Does it make sense to add https://arxiv.org/pdf/2206.01818.pdf ?

### ISSUE THREAD

**Issue by RicardoUsbeck** [KGQA/leaderboard#41]

**Comment by xixi019** [comment]
I do not think so, since they only give evaluation on subsets (1-hop, 2-hop, 3-hop) of kgqa datasets. And we do not want that, right?

**Comment by LongquanJiang** [comment]
In some ways, it is meaningful as we have already tracked the evaluation results of MetaQA and PathQuestions datasets in the leaderboard, both of which are used in this paper.

The evaluation results of these two datasets have already been updated.

close this issue if merged

**Comment by RicardoUsbeck** [comment]
Closed by https://github.com/KGQA/leaderboard/pull/42
