### ISSUE TITLE
Add KSEM papers

### ISSUE THREAD

**Issue by RicardoUsbeck** [KGQA/leaderboard#52]
- https://link.springer.com/chapter/10.1007/978-3-031-10983-6_15
- https://link.springer.com/chapter/10.1007/978-3-031-10983-6_11
- https://link.springer.com/chapter/10.1007/978-3-031-10983-6_12
- https://link.springer.com/chapter/10.1007/978-3-031-10983-6_39

**Comment by LongquanJiang** [comment]
Added 
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_15
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_11

**Comment by xixi019** [comment]
@RicardoUsbeck  https://link.springer.com/chapter/10.1007/978-3-031-10983-6_39 This paper is only tested on [SimpleQuestionFB2M](https://arxiv.org/abs/1506.02075). Me and Longquan has disagreement about whether to add this dataset to our leaderboard. Add: 1. This dataset is still valid dataset and a benchmark. Not: 1. This dataset is dependent on FB2M, which is no longer used.

**Comment by LongquanJiang** [comment]
Not: 
2. it is a dataset for simple questions. few recent qa studies used it to evaluate their method. 
3. For Simple QA systems, their performance already reached to 100%, it is impossible to have any further improvement on it.

**Comment by xixi019** [comment]
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_12 is added by #61

**Comment by RicardoUsbeck** [comment]
I am fine with not adding the FB2M results

**Comment by xixi019** [comment]
Ok, then all 4 papers apart from https://link.springer.com/chapter/10.1007/978-3-031-10983-6_39  (dependant on FB2M) are added. We can close this issue now

**Comment by RicardoUsbeck** [comment]
Link to merge pull?

**Comment by xixi019** [comment]
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_15 --> https://github.com/KGQA/leaderboard/pull/59
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_11 --> https://github.com/KGQA/leaderboard/pull/59
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_12 --> https://github.com/KGQA/leaderboard/pull/61
https://link.springer.com/chapter/10.1007/978-3-031-10983-6_39 : not added 
I have also tried to link in the pull request, somehow it does not show here

**Comment by RicardoUsbeck** [comment]
https://github.com/KGQA/leaderboard/pull/61
https://github.com/KGQA/leaderboard/pull/59
