### ISSUE TITLE
Add https://aclanthology.org/2022.coling-1.533.pdf

### ISSUE THREAD

**Issue by RicardoUsbeck** [KGQA/leaderboard#91]

**Comment by LongquanJiang** [comment]
@RicardoUsbeck It is about the complex question generation task, evaluated on BLEU, ROUGE, and METEOR, different from the evaluation metrics of KGQA in our leaderboard.

**Comment by RicardoUsbeck** [comment]
Ok, then let's close this issue. Sorry. But maybe good for @xixi019 thesis topic of question generation from medical KGQA
