### ISSUE TITLE
add  Complex Question Answering Over Temporal Knowledge Graphs

### ISSUE THREAD

**Issue by xixi019** [KGQA/leaderboard#94]
[ Complex Question Answering Over Temporal Knowledge Graphs](https://link.springer.com/chapter/10.1007/978-3-031-20891-1_6)

**Comment by huntila** [comment]
The paper doesn't introduce any new dataset.

**Comment by RicardoUsbeck** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/4354740/217021856-cf2ae510-9bb6-42cd-8591-3174b19efce9.png">
 But it has new numbers for existing datasets.

**Comment by huntila** [comment]
Shall I merge the pull request https://github.com/KGQA/leaderboard/pull/108 ?

**Comment by RicardoUsbeck** [comment]
No, a new pull request per issue is recommended

**Comment by DavidBlavid** [comment]
relevant pull request: https://github.com/KGQA/leaderboard/pull/167

**Comment by LongquanJiang** [comment]
@DavidBlavid Are these numbers correct? I cannot find them in this pull request.
<img width="808" alt="image" src="https://github.com/KGQA/leaderboard/assets/3108090/711f0661-2e75-4de4-a2c2-052139350095">

**Comment by DavidBlavid** [comment]
Because we do not differentiate between before/after, first/last and time join in cron_questions.md, i calculated the averages for the numbers. So for AE-TQ (0.542 + 0.762 + 0.737)/3 = 0.680 for Hits@1 and (0.701 + 0.793 + 0.767)/3 = 0.754 for Hits@3.

Please let me know if this is correct or if i should change it

**Comment by LongquanJiang** [comment]
Should we add a footnote for it? @xixi019

**Comment by xixi019** [comment]
> Because we do not differentiate between before/after, first/last and time join in cron_questions.md, i calculated the averages for the numbers. So for AE-TQ (0.542 + 0.762 + 0.737)/3 = 0.680 for Hits@1 and (0.701 + 0.793 + 0.767)/3 = 0.754 for Hits@3.
> 
> Please let me know if this is correct or if i should change it

I replied in this comment: https://github.com/KGQA/leaderboard/pull/167#discussion_r1228373058

**Comment by DavidBlavid** [comment]
I have created a new pull request based on the reviews: https://github.com/KGQA/leaderboard/pull/174
